package sudoku.domain;

import sudoku.board.Board;

/**
 * Interface for performing actions to rows, columns, grids or cells in the board. Usually actions will be generated by solver visitors who are able to
 * determinate result of certain cell.
 *
 * Actions are conceptually visitors so that they could visit all different elements inside sudoku board.
 */
public interface SudokuAction extends SudokuVisitor {

    void execute(Board board);
}
